import {
  PolicyConfig,
  PolicyMode,
  SpamProtectionConfig,
  FloodProtectionConfig,
  LinkProtectionConfig,
  NewMemberProtectionConfig,
  ThreatProtectionConfig,
  RaidProtectionConfig,
  ActionPolicyConfig,
  AdminAlertsConfig,
} from './types.js';

export function getDefaultPolicy(mode: PolicyMode): PolicyConfig {
  const defaults: Record<PolicyMode, PolicyConfig> = {
    RELAXED: {
      spamProtection: {
        enabled: true,
        deleteThreshold: 20,
        windowSeconds: 10,
        action: 'WARN',
        warnAfter: 5,
      },
      floodProtection: {
        enabled: false,
        maxMessages: 30,
        windowSeconds: 60,
        action: 'MUTE',
        mediaMultiplier: 2,
      },
      linkProtection: {
        enabled: true,
        shortenerAction: 'WARN',
        blockedDomains: [],
        allowedDomains: [],
        newMemberBlocks: false,
        newMemberBlockMinutes: 0,
      },
      newMemberProtection: {
        enabled: true,
        probationMinutes: 2,
        blockLinksDuringProbation: false,
        blockMediaDuringProbation: false,
        blockMentionsDuringProbation: false,
        firstMessageStrictMode: false,
        verificationRequired: false,
      },
      threatProtection: {
        enabled: true,
        scamPatternsAction: 'WARN',
        threatPatternsAction: 'WARN',
        deleteOnMatch: false,
      },
      raidProtection: {
        enabled: false,
        joinSpikeThreshold: 10,
        windowSeconds: 60,
        autoLockdown: false,
        lockdownMinutes: 30,
        restrictNewMembers: false,
        alertAdmins: false,
        paranoidDuringRaid: false,
      },
      actionPolicy: {
        warnEnabled: true,
        muteEnabled: true,
        banEnabled: true,
        deleteEnabled: true,
        kickEnabled: true,
        maxWarnsBeforeMute: 5,
        maxMutesBeforeBan: 3,
        muteDurationMinutes: 30,
      },
      adminAlerts: {
        enabled: false,
        alertOnViolation: false,
        alertOnRaid: false,
        alertChannel: null,
        minSeverity: 'CRITICAL',
      },
    },
    BALANCED: {
      spamProtection: {
        enabled: true,
        deleteThreshold: 15,
        windowSeconds: 10,
        action: 'DELETE',
        warnAfter: 3,
      },
      floodProtection: {
        enabled: true,
        maxMessages: 20,
        windowSeconds: 60,
        action: 'DELETE',
        mediaMultiplier: 1.5,
      },
      linkProtection: {
        enabled: true,
        shortenerAction: 'DELETE',
        blockedDomains: [],
        allowedDomains: [],
        newMemberBlocks: true,
        newMemberBlockMinutes: 5,
      },
      newMemberProtection: {
        enabled: true,
        probationMinutes: 5,
        blockLinksDuringProbation: true,
        blockMediaDuringProbation: false,
        blockMentionsDuringProbation: false,
        firstMessageStrictMode: false,
        verificationRequired: false,
      },
      threatProtection: {
        enabled: true,
        scamPatternsAction: 'DELETE',
        threatPatternsAction: 'DELETE',
        deleteOnMatch: true,
      },
      raidProtection: {
        enabled: true,
        joinSpikeThreshold: 15,
        windowSeconds: 60,
        autoLockdown: true,
        lockdownMinutes: 30,
        restrictNewMembers: true,
        alertAdmins: true,
        paranoidDuringRaid: false,
      },
      actionPolicy: {
        warnEnabled: true,
        muteEnabled: true,
        banEnabled: true,
        deleteEnabled: true,
        kickEnabled: true,
        maxWarnsBeforeMute: 3,
        maxMutesBeforeBan: 2,
        muteDurationMinutes: 60,
      },
      adminAlerts: {
        enabled: true,
        alertOnViolation: true,
        alertOnRaid: true,
        alertChannel: null,
        minSeverity: 'MEDIUM',
      },
    },
    STRICT: {
      spamProtection: {
        enabled: true,
        deleteThreshold: 10,
        windowSeconds: 10,
        action: 'DELETE',
        warnAfter: 2,
      },
      floodProtection: {
        enabled: true,
        maxMessages: 15,
        windowSeconds: 60,
        action: 'MUTE',
        mediaMultiplier: 1,
      },
      linkProtection: {
        enabled: true,
        shortenerAction: 'DELETE',
        blockedDomains: [],
        allowedDomains: [],
        newMemberBlocks: true,
        newMemberBlockMinutes: 15,
      },
      newMemberProtection: {
        enabled: true,
        probationMinutes: 15,
        blockLinksDuringProbation: true,
        blockMediaDuringProbation: true,
        blockMentionsDuringProbation: false,
        firstMessageStrictMode: true,
        verificationRequired: false,
      },
      threatProtection: {
        enabled: true,
        scamPatternsAction: 'MUTE',
        threatPatternsAction: 'BAN',
        deleteOnMatch: true,
      },
      raidProtection: {
        enabled: true,
        joinSpikeThreshold: 10,
        windowSeconds: 30,
        autoLockdown: true,
        lockdownMinutes: 60,
        restrictNewMembers: true,
        alertAdmins: true,
        paranoidDuringRaid: true,
      },
      actionPolicy: {
        warnEnabled: true,
        muteEnabled: true,
        banEnabled: true,
        deleteEnabled: true,
        kickEnabled: true,
        maxWarnsBeforeMute: 2,
        maxMutesBeforeBan: 1,
        muteDurationMinutes: 120,
      },
      adminAlerts: {
        enabled: true,
        alertOnViolation: true,
        alertOnRaid: true,
        alertChannel: null,
        minSeverity: 'LOW',
      },
    },
    PARANOID: {
      spamProtection: {
        enabled: true,
        deleteThreshold: 8,
        windowSeconds: 10,
        action: 'DELETE',
        warnAfter: 1,
      },
      floodProtection: {
        enabled: true,
        maxMessages: 10,
        windowSeconds: 60,
        action: 'BAN',
        mediaMultiplier: 1,
      },
      linkProtection: {
        enabled: true,
        shortenerAction: 'DELETE',
        blockedDomains: [],
        allowedDomains: [],
        newMemberBlocks: true,
        newMemberBlockMinutes: 30,
      },
      newMemberProtection: {
        enabled: true,
        probationMinutes: 30,
        blockLinksDuringProbation: true,
        blockMediaDuringProbation: true,
        blockMentionsDuringProbation: true,
        firstMessageStrictMode: true,
        verificationRequired: true,
      },
      threatProtection: {
        enabled: true,
        scamPatternsAction: 'BAN',
        threatPatternsAction: 'BAN',
        deleteOnMatch: true,
      },
      raidProtection: {
        enabled: true,
        joinSpikeThreshold: 5,
        windowSeconds: 20,
        autoLockdown: true,
        lockdownMinutes: 120,
        restrictNewMembers: true,
        alertAdmins: true,
        paranoidDuringRaid: true,
      },
      actionPolicy: {
        warnEnabled: true,
        muteEnabled: true,
        banEnabled: true,
        deleteEnabled: true,
        kickEnabled: true,
        maxWarnsBeforeMute: 1,
        maxMutesBeforeBan: 1,
        muteDurationMinutes: 240,
      },
      adminAlerts: {
        enabled: true,
        alertOnViolation: true,
        alertOnRaid: true,
        alertChannel: null,
        minSeverity: 'LOW',
      },
    },
    CUSTOM: {
      spamProtection: {
        enabled: true,
        deleteThreshold: 15,
        windowSeconds: 10,
        action: 'WARN',
        warnAfter: 3,
      },
      floodProtection: {
        enabled: true,
        maxMessages: 20,
        windowSeconds: 60,
        action: 'DELETE',
        mediaMultiplier: 1.5,
      },
      linkProtection: {
        enabled: true,
        shortenerAction: 'DELETE',
        blockedDomains: [],
        allowedDomains: [],
        newMemberBlocks: true,
        newMemberBlockMinutes: 5,
      },
      newMemberProtection: {
        enabled: true,
        probationMinutes: 5,
        blockLinksDuringProbation: true,
        blockMediaDuringProbation: false,
        blockMentionsDuringProbation: false,
        firstMessageStrictMode: false,
        verificationRequired: false,
      },
      threatProtection: {
        enabled: true,
        scamPatternsAction: 'DELETE',
        threatPatternsAction: 'DELETE',
        deleteOnMatch: true,
      },
      raidProtection: {
        enabled: true,
        joinSpikeThreshold: 10,
        windowSeconds: 60,
        autoLockdown: false,
        lockdownMinutes: 30,
        restrictNewMembers: false,
        alertAdmins: true,
        paranoidDuringRaid: false,
      },
      actionPolicy: {
        warnEnabled: true,
        muteEnabled: true,
        banEnabled: true,
        deleteEnabled: true,
        kickEnabled: true,
        maxWarnsBeforeMute: 3,
        maxMutesBeforeBan: 2,
        muteDurationMinutes: 60,
      },
      adminAlerts: {
        enabled: true,
        alertOnViolation: true,
        alertOnRaid: true,
        alertChannel: null,
        minSeverity: 'MEDIUM',
      },
    },
  };

  return defaults[mode];
}

export const policyDefaults = {
  RELAXED: getDefaultPolicy('RELAXED'),
  BALANCED: getDefaultPolicy('BALANCED'),
  STRICT: getDefaultPolicy('STRICT'),
  PARANOID: getDefaultPolicy('PARANOID'),
  CUSTOM: getDefaultPolicy('CUSTOM'),
};
