import * as fs from 'fs';
import * as path from 'path';
import { findFreePorts } from './find-free-ports';

const ENV_LOCAL_PATH = path.resolve(process.cwd(), '.env.local');
const ENV_EXAMPLE_PATH = path.resolve(process.cwd(), '.env.example');

async function main() {
  console.log('\n=== TOGI Local Setup ===\n');

  // Check if .env.local already exists
  if (fs.existsSync(ENV_LOCAL_PATH)) {
    console.log('⚠️  .env.local already exists.');
    console.log('   Creating backup at .env.local.backup\n');
    fs.copyFileSync(ENV_LOCAL_PATH, `${ENV_LOCAL_PATH}.backup`);
  }

  // Load existing env vars if .env.local exists
  let existingVars: Record<string, string> = {};
  if (fs.existsSync(ENV_LOCAL_PATH)) {
    const content = fs.readFileSync(ENV_LOCAL_PATH, 'utf-8');
    for (const line of content.split('\n')) {
      const match = line.match(/^([A-Z_]+)=(.*)$/);
      if (match) {
        existingVars[match[1]] = match[2];
      }
    }
  }

  // Find free ports
  const ports = await findFreePorts();

  console.log('Detected free ports:\n');
  for (const [name, port] of Object.entries(ports)) {
    console.log(`  ${name} = ${port}`);
  }

  // Build .env.local content
  const lines: string[] = [
    '# Generated by pnpm setup:local',
    `# Created at ${new Date().toISOString()}`,
    '',
    '# Telegram',
    `TELEGRAM_BOT_TOKEN=${existingVars.TELEGRAM_BOT_TOKEN || ''}`,
    `TELEGRAM_WEBHOOK_SECRET=${existingVars.TELEGRAM_WEBHOOK_SECRET || ''}`,
    '',
    '# API Server',
    `API_PORT=${ports.API_PORT}`,
    'API_HOST=0.0.0.0',
    '',
    '# Web Dashboard',
    `WEB_PORT=${ports.WEB_PORT}`,
    'WEB_HOST=0.0.0.0',
    '',
    '# Worker',
    `WORKER_METRICS_PORT=${ports.WORKER_METRICS_PORT}`,
    '',
    '# PostgreSQL',
    `POSTGRES_HOST=${existingVars.POSTGRES_HOST || 'localhost'}`,
    `POSTGRES_PORT=${ports.POSTGRES_PORT}`,
    `POSTGRES_USER=${existingVars.POSTGRES_USER || 'togi'}`,
    `POSTGRES_PASSWORD=${existingVars.POSTGRES_PASSWORD || 'togi_dev_password'}`,
    `POSTGRES_DB=${existingVars.POSTGRES_DB || 'togi'}`,
    '',
    '# Redis',
    `REDIS_HOST=${existingVars.REDIS_HOST || 'localhost'}`,
    `REDIS_PORT=${ports.REDIS_PORT}`,
    `REDIS_PASSWORD=${existingVars.REDIS_PASSWORD || 'togi_dev_password'}`,
    '',
    '# JWT',
    `JWT_SECRET=${existingVars.JWT_SECRET || 'change-me-in-production'}`,
    '',
    '# Environment',
    'NODE_ENV=development',
    'LOG_LEVEL=debug',
  ];

  fs.writeFileSync(ENV_LOCAL_PATH, lines.join('\n') + '\n');

  console.log('\n✅ .env.local created successfully.\n');
  console.log('Next steps:');
  console.log('  1. Add your TELEGRAM_BOT_TOKEN to .env.local');
  console.log('  2. Run: pnpm install');
  console.log('  3. Run: pnpm run docker:up');
  console.log('  4. Run: pnpm run db:migrate\n');
}

main().catch((err) => {
  console.error('Setup failed:', err);
  process.exit(1);
});
